name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install git2.h
      run: sudo apt-get install libgit2-dev

    - name: Run make
      run: make


#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
